sudo: true
language: java
# Mini Accumulo does not compile w/ Java 9+ https://github.com/apache/accumulo-website/issues/147
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.npm"
  - node_modules
stages:
  - name: install
    if: branch != release
  - name: test
    if: branch != release AND !(tag IS present)
  - name: deploy
    if: tag IS present OR type = cron
  - name: deploy-feature
    if: tag IS present OR type = cron
  - name: deploy-karaf
    if: tag IS present
jobs:
  include:
    - stage: install
      name: "Coalesce"
      install:
#        - sudo keytool -importcert -v -trustcacerts -alias devforce -keystore "$JAVA_HOME/lib/security/cacerts" -storepass changeit --noprompt -file src/Coalesce.Framework.Persister.Elasticsearch/devforce_DoD_Root.crt
        - cp .travis.settings.xml $HOME/.m2/settings.xml
      script: mvn install -Dfindbugs.skip=false -DskipTests -P bundles -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

    - stage: install
      name: "Coalesce UI"
      install: npm config set cache $HOME/.npm
      script:
        - unset CI
        - mvn install -f src/Coalesce.React -DskipTests -P react -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

    - stage: test
      name: "Coalesce"
      install:
#        - sudo keytool -importcert -v -trustcacerts -alias devforce -keystore "$JAVA_HOME/lib/security/cacerts" -storepass changeit --noprompt -file src/Coalesce.Framework.Persister.Elasticsearch/devforce_DoD_Root.crt
        - cp .travis.settings.xml $HOME/.m2/settings.xml
      script: mvn verify -Djacoco.skip=false -fae -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

    - stage: deploy
      name: "Coalesce"
      install: skip
      script: mvn deploy -P bundles -DskipTests -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

    - stage: deploy
      name: "Coalesce UI"
      install: npm config set cache $HOME/.npm
      script: 
        - unset CI 
        - mvn deploy -f src/Coalesce.React -DskipTests -P react -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

    - stage: deploy
      name: "Coalesce Documentation"
      install:
        # Compute Code Coverage / Find Bugs
#        - sudo keytool -importcert -v -trustcacerts -alias devforce -keystore "$JAVA_HOME/jre/lib/security/cacerts" -storepass changeit --noprompt -file src/Coalesce.Framework.Persister.Elasticsearch/devforce_DoD_Root.crt
        - cp .travis.settings.xml $HOME/.m2/settings.xml
      before_script:
        # Copy Classes
        - mvn install -Dfindbugs.skip=false -Djacoco.skip=false -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        - mkdir -p target/classes/com
        - find -type d -path '**/classes/com/incadencecorp' -exec cp -at target/classes/com/. {} +
      script:
        # Create Site and Deploy
        - mvn site -DskipDocker -Dfindbugs.skip=false -Djacoco.skip=false -Dcheckstyle.skip=false  -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        - mvn site -f src/pyCoalesce -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        - cp -r src/pyCoalesce/target/site target/site/pycoalesce
        - mvn deploy -f src/Coalesce.Dist/coalesce-javadocs  -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

    - stage: deploy-feature
      name: "Coalesce Feature"
      install: skip
      script:
        - mvn deploy -f src/Coalesce.Feature -DskipTests -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

    - stage: deploy-karaf
      name: "Coalesce Karaf"
      install: skip
      script:
        - mvn deploy -f src/Coalesce.Dist/coalesce-karaf-dist -DskipTests -DskipDocker -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
