sudo: true
language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - node_modules
install:
- cp .travis.settings.xml $HOME/.m2/settings.xml
- travis_retry mvn install -DskipTests -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
script:
- travis_retry mvn verify -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
after_success:
deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -P bundles,dist,react"
  skip_cleanup: true
  on:
    branch: master

