version: "2"

volumes:
  db-backups:
  geoserver-data:

networks:
  coalesce_network:
    external:
      name: coalesce

services:
    db:
      image: kartoza/postgis:10.0-2.4
      hostname: postgis
      volumes:
        #- ./pg/postgres_data:/var/lib/postgresql
        - db-backups:/backups
      ports:
        - "25432:5432"
      networks:
        - coalesce_network
      environment:
        - USERNAME=docker
        - PASS=docker
        - ALLOW_IP_RANGE=172.20.0.0/24
      restart: unless-stopped
    geoserver:
      image: eeacms/elasticgeo #kartoza/geoserver:2.12.0
      hostname: geoserver
      volumes:
        - geoserver-data:/opt/geoserver/data_dir
      ports:
        - "8080:8080"
      networks:
        - coalesce_network
      links:
        - db:db
      restart: unless-stopped
      user: root
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
        container_name: coalesce-elasticsearch
        environment:
            - cluster.name=elasticsearch
            - http.host=0.0.0.0
            - http.port=9200
            - network.publish_host=0.0.0.0
            - transport.tcp.port=9300
            - discovery.type=single-node
            - xpack.security.enabled=false
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
          - coalesce_network
        restart: unless-stopped
    kibana5:
      image: docker.elastic.co/kibana/kibana:5.4.0
      container_name: coalesce-kibana
      environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200
      ports:
        - "5601:5601"
      depends_on:
        - "elasticsearch"
      networks:
        - coalesce_network
      restart: unless-stopped
    coalesce:
      image: incadencecorp/coalesce-ext-karaf:0.0.36-SNAPSHOT
      container_name: coalesce
      depends_on:
        - "elasticsearch"
      ports:
          - "8101:8101"
          - "8181:8181"
      networks:
        - coalesce_network
      restart: unless-stopped
