//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://dataservice.irems.com", ConfigurationName="CoalescePersistorPortType")]
public interface CoalescePersistorPortType
{
    
    // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="urn:getEntityXmlByIdType", ReplyAction="urn:getEntityXmlByIdTypeResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    getEntityXmlByIdTypeResponse getEntityXmlByIdType(getEntityXmlByIdTypeRequest request);
    
    // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="urn:getEntityXmlByKey", ReplyAction="urn:getEntityXmlByKeyResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    getEntityXmlByKeyResponse getEntityXmlByKey(getEntityXmlByKeyRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="getEntityXmlByIdType", WrapperNamespace="http://dataservice.irems.com", IsWrapped=true)]
public partial class getEntityXmlByIdTypeRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dataservice.irems.com", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string EntityId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dataservice.irems.com", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string EntityIdType;
    
    public getEntityXmlByIdTypeRequest()
    {
    }
    
    public getEntityXmlByIdTypeRequest(string EntityId, string EntityIdType)
    {
        this.EntityId = EntityId;
        this.EntityIdType = EntityIdType;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="getEntityXmlByIdTypeResponse", WrapperNamespace="http://dataservice.irems.com", IsWrapped=true)]
public partial class getEntityXmlByIdTypeResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dataservice.irems.com", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
    public string[] @return;
    
    public getEntityXmlByIdTypeResponse()
    {
    }
    
    public getEntityXmlByIdTypeResponse(string[] @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="getEntityXmlByKey", WrapperNamespace="http://dataservice.irems.com", IsWrapped=true)]
public partial class getEntityXmlByKeyRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dataservice.irems.com", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Key;
    
    public getEntityXmlByKeyRequest()
    {
    }
    
    public getEntityXmlByKeyRequest(string Key)
    {
        this.Key = Key;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="getEntityXmlByKeyResponse", WrapperNamespace="http://dataservice.irems.com", IsWrapped=true)]
public partial class getEntityXmlByKeyResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dataservice.irems.com", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string @return;
    
    public getEntityXmlByKeyResponse()
    {
    }
    
    public getEntityXmlByKeyResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface CoalescePersistorPortTypeChannel : CoalescePersistorPortType, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class CoalescePersistorPortTypeClient : System.ServiceModel.ClientBase<CoalescePersistorPortType>, CoalescePersistorPortType
{
    
    public CoalescePersistorPortTypeClient()
    {
    }
    
    public CoalescePersistorPortTypeClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CoalescePersistorPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CoalescePersistorPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CoalescePersistorPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getEntityXmlByIdTypeResponse CoalescePersistorPortType.getEntityXmlByIdType(getEntityXmlByIdTypeRequest request)
    {
        return base.Channel.getEntityXmlByIdType(request);
    }
    
    public string[] getEntityXmlByIdType(string EntityId, string EntityIdType)
    {
        getEntityXmlByIdTypeRequest inValue = new getEntityXmlByIdTypeRequest();
        inValue.EntityId = EntityId;
        inValue.EntityIdType = EntityIdType;
        getEntityXmlByIdTypeResponse retVal = ((CoalescePersistorPortType)(this)).getEntityXmlByIdType(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getEntityXmlByKeyResponse CoalescePersistorPortType.getEntityXmlByKey(getEntityXmlByKeyRequest request)
    {
        return base.Channel.getEntityXmlByKey(request);
    }
    
    public string getEntityXmlByKey(string Key)
    {
        getEntityXmlByKeyRequest inValue = new getEntityXmlByKeyRequest();
        inValue.Key = Key;
        getEntityXmlByKeyResponse retVal = ((CoalescePersistorPortType)(this)).getEntityXmlByKey(inValue);
        return retVal.@return;
    }
}
