//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.16 at 03:25:33 PM EDT 
//


package com.incadencecorp.coalesce.framework.generatedjaxb;

import java.util.Locale;
import javax.xml.bind.annotation.adapters.XmlAdapter;

public class Adapter2
    extends XmlAdapter<String, Locale>
{


    public Locale unmarshal(String value) {
        return (com.incadencecorp.coalesce.common.helpers.LocaleConverter.parseLocale(value));
    }

    public String marshal(Locale value) {
        return (com.incadencecorp.coalesce.common.helpers.LocaleConverter.printLocale(value));
    }

}
