//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.14 at 04:49:03 PM EDT 
//


package com.incadencecorp.coalesce.framework.generatedjaxb;

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;
import org.joda.time.DateTime;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="datecreated" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="lastmodified" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="entity1key" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="entity1name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="entity1source" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="entity1version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="linktype" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="entity2key" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="entity2name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="entity2source" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="entity2version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="classificationmarking" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="modifiedby" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="inputlang" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;anyAttribute processContents='skip' namespace='##other'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "linkage")
public class Linkage {

    @XmlAttribute(name = "key")
    protected String key;
    @XmlAttribute(name = "datecreated")
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "date")
    protected DateTime datecreated;
    @XmlAttribute(name = "lastmodified")
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "date")
    protected DateTime lastmodified;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "entity1key")
    protected String entity1Key;
    @XmlAttribute(name = "entity1name")
    protected String entity1Name;
    @XmlAttribute(name = "entity1source")
    protected String entity1Source;
    @XmlAttribute(name = "entity1version")
    protected String entity1Version;
    @XmlAttribute(name = "linktype")
    protected String linktype;
    @XmlAttribute(name = "entity2key")
    protected String entity2Key;
    @XmlAttribute(name = "entity2name")
    protected String entity2Name;
    @XmlAttribute(name = "entity2source")
    protected String entity2Source;
    @XmlAttribute(name = "entity2version")
    protected String entity2Version;
    @XmlAttribute(name = "classificationmarking")
    protected String classificationmarking;
    @XmlAttribute(name = "modifiedby")
    protected String modifiedby;
    @XmlAttribute(name = "inputlang")
    protected String inputlang;
    @XmlAttribute(name = "status")
    protected String status;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the datecreated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public DateTime getDatecreated() {
        return datecreated;
    }

    /**
     * Sets the value of the datecreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatecreated(DateTime value) {
        this.datecreated = value;
    }

    /**
     * Gets the value of the lastmodified property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public DateTime getLastmodified() {
        return lastmodified;
    }

    /**
     * Sets the value of the lastmodified property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastmodified(DateTime value) {
        this.lastmodified = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the entity1Key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntity1Key() {
        return entity1Key;
    }

    /**
     * Sets the value of the entity1Key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntity1Key(String value) {
        this.entity1Key = value;
    }

    /**
     * Gets the value of the entity1Name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntity1Name() {
        return entity1Name;
    }

    /**
     * Sets the value of the entity1Name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntity1Name(String value) {
        this.entity1Name = value;
    }

    /**
     * Gets the value of the entity1Source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntity1Source() {
        return entity1Source;
    }

    /**
     * Sets the value of the entity1Source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntity1Source(String value) {
        this.entity1Source = value;
    }

    /**
     * Gets the value of the entity1Version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntity1Version() {
        return entity1Version;
    }

    /**
     * Sets the value of the entity1Version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntity1Version(String value) {
        this.entity1Version = value;
    }

    /**
     * Gets the value of the linktype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinktype() {
        return linktype;
    }

    /**
     * Sets the value of the linktype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinktype(String value) {
        this.linktype = value;
    }

    /**
     * Gets the value of the entity2Key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntity2Key() {
        return entity2Key;
    }

    /**
     * Sets the value of the entity2Key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntity2Key(String value) {
        this.entity2Key = value;
    }

    /**
     * Gets the value of the entity2Name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntity2Name() {
        return entity2Name;
    }

    /**
     * Sets the value of the entity2Name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntity2Name(String value) {
        this.entity2Name = value;
    }

    /**
     * Gets the value of the entity2Source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntity2Source() {
        return entity2Source;
    }

    /**
     * Sets the value of the entity2Source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntity2Source(String value) {
        this.entity2Source = value;
    }

    /**
     * Gets the value of the entity2Version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntity2Version() {
        return entity2Version;
    }

    /**
     * Sets the value of the entity2Version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntity2Version(String value) {
        this.entity2Version = value;
    }

    /**
     * Gets the value of the classificationmarking property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassificationmarking() {
        return classificationmarking;
    }

    /**
     * Sets the value of the classificationmarking property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassificationmarking(String value) {
        this.classificationmarking = value;
    }

    /**
     * Gets the value of the modifiedby property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifiedby() {
        return modifiedby;
    }

    /**
     * Sets the value of the modifiedby property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifiedby(String value) {
        this.modifiedby = value;
    }

    /**
     * Gets the value of the inputlang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputlang() {
        return inputlang;
    }

    /**
     * Sets the value of the inputlang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputlang(String value) {
        this.inputlang = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
