//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.16 at 03:25:33 PM EDT 
//


package com.incadencecorp.coalesce.framework.generatedjaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.incadencecorp.coalesce.framework.generatedjaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.incadencecorp.coalesce.framework.generatedjaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link Fieldhistory }
     * 
     */
    public Fieldhistory createFieldhistory() {
        return new Fieldhistory();
    }

    /**
     * Create an instance of {@link Record }
     * 
     */
    public Record createRecord() {
        return new Record();
    }

    /**
     * Create an instance of {@link NewDataSet }
     * 
     */
    public NewDataSet createNewDataSet() {
        return new NewDataSet();
    }

    /**
     * Create an instance of {@link Entity }
     * 
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link Linkagesection }
     * 
     */
    public Linkagesection createLinkagesection() {
        return new Linkagesection();
    }

    /**
     * Create an instance of {@link Linkage }
     * 
     */
    public Linkage createLinkage() {
        return new Linkage();
    }

    /**
     * Create an instance of {@link Section }
     * 
     */
    public Section createSection() {
        return new Section();
    }

    /**
     * Create an instance of {@link Recordset }
     * 
     */
    public Recordset createRecordset() {
        return new Recordset();
    }

    /**
     * Create an instance of {@link Fielddefinition }
     * 
     */
    public Fielddefinition createFielddefinition() {
        return new Fielddefinition();
    }

}
