//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceTester.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.irems.proto.com/", ConfigurationName="ServiceReference1.ICoalesceDataService")]
    public interface ICoalesceDataService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.irems.proto.com/ICoalesceDataService/getFieldValueRequest", ReplyAction="http://services.irems.proto.com/ICoalesceDataService/getFieldValueResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        DataServiceTester.ServiceReference1.getFieldValueResponse getFieldValue(DataServiceTester.ServiceReference1.getFieldValueRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.irems.proto.com/ICoalesceDataService/getEntityRequest", ReplyAction="http://services.irems.proto.com/ICoalesceDataService/getEntityResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        DataServiceTester.ServiceReference1.getEntityResponse getEntity(DataServiceTester.ServiceReference1.getEntityRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.irems.proto.com/ICoalesceDataService/getEntityKeysRequest", ReplyAction="http://services.irems.proto.com/ICoalesceDataService/getEntityKeysResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        DataServiceTester.ServiceReference1.getEntityKeysResponse getEntityKeys(DataServiceTester.ServiceReference1.getEntityKeysRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.irems.proto.com/ICoalesceDataService/setEntityRequest", ReplyAction="http://services.irems.proto.com/ICoalesceDataService/setEntityResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractStringBuilder))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        DataServiceTester.ServiceReference1.setEntityResponse setEntity(DataServiceTester.ServiceReference1.setEntityRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.irems.proto.com/ICoalesceDataService/getEntityXMLRequest", ReplyAction="http://services.irems.proto.com/ICoalesceDataService/getEntityXMLResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractStringBuilder))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        DataServiceTester.ServiceReference1.getEntityXMLResponse getEntityXML(DataServiceTester.ServiceReference1.getEntityXMLRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.irems.proto.com/ICoalesceDataService/getXPathRequest", ReplyAction="http://services.irems.proto.com/ICoalesceDataService/getXPathResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractStringBuilder))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        DataServiceTester.ServiceReference1.getXPathResponse getXPath(DataServiceTester.ServiceReference1.getXPathRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.irems.proto.com/ICoalesceDataService/getEntityByNameRequest", ReplyAction="http://services.irems.proto.com/ICoalesceDataService/getEntityByNameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractStringBuilder))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        DataServiceTester.ServiceReference1.getEntityByNameResponse getEntityByName(DataServiceTester.ServiceReference1.getEntityByNameRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.irems.proto.com/ICoalesceDataService/getEntityXMLKeysRequest", ReplyAction="http://services.irems.proto.com/ICoalesceDataService/getEntityXMLKeysResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractStringBuilder))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        DataServiceTester.ServiceReference1.getEntityXMLKeysResponse getEntityXMLKeys(DataServiceTester.ServiceReference1.getEntityXMLKeysRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.irems.proto.com/ICoalesceDataService/getEntityXMLByNameRequest", ReplyAction="http://services.irems.proto.com/ICoalesceDataService/getEntityXMLByNameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractStringBuilder))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        DataServiceTester.ServiceReference1.getEntityXMLByNameResponse getEntityXMLByName(DataServiceTester.ServiceReference1.getEntityXMLByNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFieldValue", WrapperNamespace="http://services.irems.proto.com/", IsWrapped=true)]
    public partial class getFieldValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.irems.proto.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getFieldValueRequest() {
        }
        
        public getFieldValueRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFieldValueResponse", WrapperNamespace="http://services.irems.proto.com/", IsWrapped=true)]
    public partial class getFieldValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.irems.proto.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getFieldValueResponse() {
        }
        
        public getFieldValueResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEntity", WrapperNamespace="http://services.irems.proto.com/", IsWrapped=true)]
    public partial class getEntityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.irems.proto.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getEntityRequest() {
        }
        
        public getEntityRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEntityResponse", WrapperNamespace="http://services.irems.proto.com/", IsWrapped=true)]
    public partial class getEntityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.irems.proto.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getEntityResponse() {
        }
        
        public getEntityResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEntityKeys", WrapperNamespace="http://services.irems.proto.com/", IsWrapped=true)]
    public partial class getEntityKeysRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.irems.proto.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.irems.proto.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public getEntityKeysRequest() {
        }
        
        public getEntityKeysRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEntityKeysResponse", WrapperNamespace="http://services.irems.proto.com/", IsWrapped=true)]
    public partial class getEntityKeysResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.irems.proto.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public getEntityKeysResponse() {
        }
        
        public getEntityKeysResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.irems.proto.com/")]
    public partial class jEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dateCreatedField;
        
        private string entityIdField;
        
        private string entityIdTypeField;
        
        private stringBuilder entityXmlField;
        
        private string lastModifiedField;
        
        private string nameField;
        
        private string objectKeyField;
        
        private string sourceField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string dateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
                this.RaisePropertyChanged("dateCreated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string entityId {
            get {
                return this.entityIdField;
            }
            set {
                this.entityIdField = value;
                this.RaisePropertyChanged("entityId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string entityIdType {
            get {
                return this.entityIdTypeField;
            }
            set {
                this.entityIdTypeField = value;
                this.RaisePropertyChanged("entityIdType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public stringBuilder entityXml {
            get {
                return this.entityXmlField;
            }
            set {
                this.entityXmlField = value;
                this.RaisePropertyChanged("entityXml");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string lastModified {
            get {
                return this.lastModifiedField;
            }
            set {
                this.lastModifiedField = value;
                this.RaisePropertyChanged("lastModified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string objectKey {
            get {
                return this.objectKeyField;
            }
            set {
                this.objectKeyField = value;
                this.RaisePropertyChanged("objectKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.irems.proto.com/")]
    public partial class stringBuilder : abstractStringBuilder {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(stringBuilder))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.irems.proto.com/")]
    public abstract partial class abstractStringBuilder : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setEntity", WrapperNamespace="http://services.irems.proto.com/", IsWrapped=true)]
    public partial class setEntityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.irems.proto.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DataServiceTester.ServiceReference1.jEntity arg0;
        
        public setEntityRequest() {
        }
        
        public setEntityRequest(DataServiceTester.ServiceReference1.jEntity arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setEntityResponse", WrapperNamespace="http://services.irems.proto.com/", IsWrapped=true)]
    public partial class setEntityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.irems.proto.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public setEntityResponse() {
        }
        
        public setEntityResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEntityXML", WrapperNamespace="http://services.irems.proto.com/", IsWrapped=true)]
    public partial class getEntityXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.irems.proto.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getEntityXMLRequest() {
        }
        
        public getEntityXMLRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEntityXMLResponse", WrapperNamespace="http://services.irems.proto.com/", IsWrapped=true)]
    public partial class getEntityXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.irems.proto.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getEntityXMLResponse() {
        }
        
        public getEntityXMLResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getXPath", WrapperNamespace="http://services.irems.proto.com/", IsWrapped=true)]
    public partial class getXPathRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.irems.proto.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.irems.proto.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.irems.proto.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public getXPathRequest() {
        }
        
        public getXPathRequest(string arg0, string arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getXPathResponse", WrapperNamespace="http://services.irems.proto.com/", IsWrapped=true)]
    public partial class getXPathResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.irems.proto.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getXPathResponse() {
        }
        
        public getXPathResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEntityByName", WrapperNamespace="http://services.irems.proto.com/", IsWrapped=true)]
    public partial class getEntityByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.irems.proto.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.irems.proto.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.irems.proto.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public getEntityByNameRequest() {
        }
        
        public getEntityByNameRequest(string arg0, string arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEntityByNameResponse", WrapperNamespace="http://services.irems.proto.com/", IsWrapped=true)]
    public partial class getEntityByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.irems.proto.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getEntityByNameResponse() {
        }
        
        public getEntityByNameResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEntityXMLKeys", WrapperNamespace="http://services.irems.proto.com/", IsWrapped=true)]
    public partial class getEntityXMLKeysRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.irems.proto.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.irems.proto.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public getEntityXMLKeysRequest() {
        }
        
        public getEntityXMLKeysRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEntityXMLKeysResponse", WrapperNamespace="http://services.irems.proto.com/", IsWrapped=true)]
    public partial class getEntityXMLKeysResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.irems.proto.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public getEntityXMLKeysResponse() {
        }
        
        public getEntityXMLKeysResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEntityXMLByName", WrapperNamespace="http://services.irems.proto.com/", IsWrapped=true)]
    public partial class getEntityXMLByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.irems.proto.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.irems.proto.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.irems.proto.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public getEntityXMLByNameRequest() {
        }
        
        public getEntityXMLByNameRequest(string arg0, string arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEntityXMLByNameResponse", WrapperNamespace="http://services.irems.proto.com/", IsWrapped=true)]
    public partial class getEntityXMLByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.irems.proto.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getEntityXMLByNameResponse() {
        }
        
        public getEntityXMLByNameResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICoalesceDataServiceChannel : DataServiceTester.ServiceReference1.ICoalesceDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CoalesceDataServiceClient : System.ServiceModel.ClientBase<DataServiceTester.ServiceReference1.ICoalesceDataService>, DataServiceTester.ServiceReference1.ICoalesceDataService {
        
        public CoalesceDataServiceClient() {
        }
        
        public CoalesceDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CoalesceDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoalesceDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoalesceDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataServiceTester.ServiceReference1.getFieldValueResponse DataServiceTester.ServiceReference1.ICoalesceDataService.getFieldValue(DataServiceTester.ServiceReference1.getFieldValueRequest request) {
            return base.Channel.getFieldValue(request);
        }
        
        public string getFieldValue(string arg0) {
            DataServiceTester.ServiceReference1.getFieldValueRequest inValue = new DataServiceTester.ServiceReference1.getFieldValueRequest();
            inValue.arg0 = arg0;
            DataServiceTester.ServiceReference1.getFieldValueResponse retVal = ((DataServiceTester.ServiceReference1.ICoalesceDataService)(this)).getFieldValue(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataServiceTester.ServiceReference1.getEntityResponse DataServiceTester.ServiceReference1.ICoalesceDataService.getEntity(DataServiceTester.ServiceReference1.getEntityRequest request) {
            return base.Channel.getEntity(request);
        }
        
        public string getEntity(string arg0) {
            DataServiceTester.ServiceReference1.getEntityRequest inValue = new DataServiceTester.ServiceReference1.getEntityRequest();
            inValue.arg0 = arg0;
            DataServiceTester.ServiceReference1.getEntityResponse retVal = ((DataServiceTester.ServiceReference1.ICoalesceDataService)(this)).getEntity(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataServiceTester.ServiceReference1.getEntityKeysResponse DataServiceTester.ServiceReference1.ICoalesceDataService.getEntityKeys(DataServiceTester.ServiceReference1.getEntityKeysRequest request) {
            return base.Channel.getEntityKeys(request);
        }
        
        public string[] getEntityKeys(string arg0, string arg1) {
            DataServiceTester.ServiceReference1.getEntityKeysRequest inValue = new DataServiceTester.ServiceReference1.getEntityKeysRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            DataServiceTester.ServiceReference1.getEntityKeysResponse retVal = ((DataServiceTester.ServiceReference1.ICoalesceDataService)(this)).getEntityKeys(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataServiceTester.ServiceReference1.setEntityResponse DataServiceTester.ServiceReference1.ICoalesceDataService.setEntity(DataServiceTester.ServiceReference1.setEntityRequest request) {
            return base.Channel.setEntity(request);
        }
        
        public bool setEntity(DataServiceTester.ServiceReference1.jEntity arg0) {
            DataServiceTester.ServiceReference1.setEntityRequest inValue = new DataServiceTester.ServiceReference1.setEntityRequest();
            inValue.arg0 = arg0;
            DataServiceTester.ServiceReference1.setEntityResponse retVal = ((DataServiceTester.ServiceReference1.ICoalesceDataService)(this)).setEntity(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataServiceTester.ServiceReference1.getEntityXMLResponse DataServiceTester.ServiceReference1.ICoalesceDataService.getEntityXML(DataServiceTester.ServiceReference1.getEntityXMLRequest request) {
            return base.Channel.getEntityXML(request);
        }
        
        public string getEntityXML(string arg0) {
            DataServiceTester.ServiceReference1.getEntityXMLRequest inValue = new DataServiceTester.ServiceReference1.getEntityXMLRequest();
            inValue.arg0 = arg0;
            DataServiceTester.ServiceReference1.getEntityXMLResponse retVal = ((DataServiceTester.ServiceReference1.ICoalesceDataService)(this)).getEntityXML(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataServiceTester.ServiceReference1.getXPathResponse DataServiceTester.ServiceReference1.ICoalesceDataService.getXPath(DataServiceTester.ServiceReference1.getXPathRequest request) {
            return base.Channel.getXPath(request);
        }
        
        public string getXPath(string arg0, string arg1, string arg2) {
            DataServiceTester.ServiceReference1.getXPathRequest inValue = new DataServiceTester.ServiceReference1.getXPathRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            DataServiceTester.ServiceReference1.getXPathResponse retVal = ((DataServiceTester.ServiceReference1.ICoalesceDataService)(this)).getXPath(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataServiceTester.ServiceReference1.getEntityByNameResponse DataServiceTester.ServiceReference1.ICoalesceDataService.getEntityByName(DataServiceTester.ServiceReference1.getEntityByNameRequest request) {
            return base.Channel.getEntityByName(request);
        }
        
        public string getEntityByName(string arg0, string arg1, string arg2) {
            DataServiceTester.ServiceReference1.getEntityByNameRequest inValue = new DataServiceTester.ServiceReference1.getEntityByNameRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            DataServiceTester.ServiceReference1.getEntityByNameResponse retVal = ((DataServiceTester.ServiceReference1.ICoalesceDataService)(this)).getEntityByName(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataServiceTester.ServiceReference1.getEntityXMLKeysResponse DataServiceTester.ServiceReference1.ICoalesceDataService.getEntityXMLKeys(DataServiceTester.ServiceReference1.getEntityXMLKeysRequest request) {
            return base.Channel.getEntityXMLKeys(request);
        }
        
        public string[] getEntityXMLKeys(string arg0, string arg1) {
            DataServiceTester.ServiceReference1.getEntityXMLKeysRequest inValue = new DataServiceTester.ServiceReference1.getEntityXMLKeysRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            DataServiceTester.ServiceReference1.getEntityXMLKeysResponse retVal = ((DataServiceTester.ServiceReference1.ICoalesceDataService)(this)).getEntityXMLKeys(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataServiceTester.ServiceReference1.getEntityXMLByNameResponse DataServiceTester.ServiceReference1.ICoalesceDataService.getEntityXMLByName(DataServiceTester.ServiceReference1.getEntityXMLByNameRequest request) {
            return base.Channel.getEntityXMLByName(request);
        }
        
        public string getEntityXMLByName(string arg0, string arg1, string arg2) {
            DataServiceTester.ServiceReference1.getEntityXMLByNameRequest inValue = new DataServiceTester.ServiceReference1.getEntityXMLByNameRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            DataServiceTester.ServiceReference1.getEntityXMLByNameResponse retVal = ((DataServiceTester.ServiceReference1.ICoalesceDataService)(this)).getEntityXMLByName(inValue);
            return retVal.@return;
        }
    }
}
