//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.25 at 11:36:51 AM EDT 
//


package Coalesce.Framework.GeneratedJAXB;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the Coalesce.Framework.GeneratedJAXB package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Recset_QNAME = new QName("", "recset");
    private final static QName _Fielddef_QNAME = new QName("", "fielddef");
    private final static QName _Rec_QNAME = new QName("", "rec");
    private final static QName _Fieldhist_QNAME = new QName("", "fieldhist");
    private final static QName _Sec_QNAME = new QName("", "sec");
    private final static QName _Link_QNAME = new QName("", "link");
    private final static QName _Fld_QNAME = new QName("", "fld");
    private final static QName _Linkagesec_QNAME = new QName("", "linkagesec");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: Coalesce.Framework.GeneratedJAXB
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Fieldhistory }
     * 
     */
    public Fieldhistory createFieldhistory() {
        return new Fieldhistory();
    }

    /**
     * Create an instance of {@link NewDataSet }
     * 
     */
    public NewDataSet createNewDataSet() {
        return new NewDataSet();
    }

    /**
     * Create an instance of {@link Linkagesection }
     * 
     */
    public Linkagesection createLinkagesection() {
        return new Linkagesection();
    }

    /**
     * Create an instance of {@link Record }
     * 
     */
    public Record createRecord() {
        return new Record();
    }

    /**
     * Create an instance of {@link Recordset }
     * 
     */
    public Recordset createRecordset() {
        return new Recordset();
    }

    /**
     * Create an instance of {@link Entity }
     * 
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link Linkage }
     * 
     */
    public Linkage createLinkage() {
        return new Linkage();
    }

    /**
     * Create an instance of {@link Section }
     * 
     */
    public Section createSection() {
        return new Section();
    }

    /**
     * Create an instance of {@link Fielddefinition }
     * 
     */
    public Fielddefinition createFielddefinition() {
        return new Fielddefinition();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Recordset }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "recset")
    public JAXBElement<Recordset> createRecset(Recordset value) {
        return new JAXBElement<Recordset>(_Recset_QNAME, Recordset.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Fielddefinition }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fielddef")
    public JAXBElement<Fielddefinition> createFielddef(Fielddefinition value) {
        return new JAXBElement<Fielddefinition>(_Fielddef_QNAME, Fielddefinition.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Record }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rec")
    public JAXBElement<Record> createRec(Record value) {
        return new JAXBElement<Record>(_Rec_QNAME, Record.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Fieldhistory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fieldhist")
    public JAXBElement<Fieldhistory> createFieldhist(Fieldhistory value) {
        return new JAXBElement<Fieldhistory>(_Fieldhist_QNAME, Fieldhistory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Section }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sec")
    public JAXBElement<Section> createSec(Section value) {
        return new JAXBElement<Section>(_Sec_QNAME, Section.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Linkage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "link")
    public JAXBElement<Linkage> createLink(Linkage value) {
        return new JAXBElement<Linkage>(_Link_QNAME, Linkage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Field }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fld")
    public JAXBElement<Field> createFld(Field value) {
        return new JAXBElement<Field>(_Fld_QNAME, Field.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Linkagesection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "linkagesec")
    public JAXBElement<Linkagesection> createLinkagesec(Linkagesection value) {
        return new JAXBElement<Linkagesection>(_Linkagesec_QNAME, Linkagesection.class, null, value);
    }

}
