//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.25 at 02:21:40 PM EDT 
//


package Coalesce.Framework.GeneratedJAXB;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the Coalesce.Framework.GeneratedJAXB package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SectionNode_QNAME = new QName("", "section_node");
    private final static QName _RecordNode_QNAME = new QName("", "record_node");
    private final static QName _FieldNode_QNAME = new QName("", "field_node");
    private final static QName _LinkagesectionNode_QNAME = new QName("", "linkagesection_node");
    private final static QName _RecordsetNode_QNAME = new QName("", "recordset_node");
    private final static QName _FieldhistoryNode_QNAME = new QName("", "fieldhistory_node");
    private final static QName _LinkageNode_QNAME = new QName("", "linkage_node");
    private final static QName _FielddefinitionNode_QNAME = new QName("", "fielddefinition_node");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: Coalesce.Framework.GeneratedJAXB
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Linkagesection }
     * 
     */
    public Linkagesection createLinkagesection() {
        return new Linkagesection();
    }

    /**
     * Create an instance of {@link Fieldhistory }
     * 
     */
    public Fieldhistory createFieldhistory() {
        return new Fieldhistory();
    }

    /**
     * Create an instance of {@link Fielddefinition }
     * 
     */
    public Fielddefinition createFielddefinition() {
        return new Fielddefinition();
    }

    /**
     * Create an instance of {@link Linkage }
     * 
     */
    public Linkage createLinkage() {
        return new Linkage();
    }

    /**
     * Create an instance of {@link Entity }
     * 
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link Section }
     * 
     */
    public Section createSection() {
        return new Section();
    }

    /**
     * Create an instance of {@link Recordset }
     * 
     */
    public Recordset createRecordset() {
        return new Recordset();
    }

    /**
     * Create an instance of {@link Record }
     * 
     */
    public Record createRecord() {
        return new Record();
    }

    /**
     * Create an instance of {@link NewDataSet }
     * 
     */
    public NewDataSet createNewDataSet() {
        return new NewDataSet();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Section }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "section_node")
    public JAXBElement<Section> createSectionNode(Section value) {
        return new JAXBElement<Section>(_SectionNode_QNAME, Section.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Record }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "record_node")
    public JAXBElement<Record> createRecordNode(Record value) {
        return new JAXBElement<Record>(_RecordNode_QNAME, Record.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Field }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "field_node")
    public JAXBElement<Field> createFieldNode(Field value) {
        return new JAXBElement<Field>(_FieldNode_QNAME, Field.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Linkagesection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "linkagesection_node")
    public JAXBElement<Linkagesection> createLinkagesectionNode(Linkagesection value) {
        return new JAXBElement<Linkagesection>(_LinkagesectionNode_QNAME, Linkagesection.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Recordset }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "recordset_node")
    public JAXBElement<Recordset> createRecordsetNode(Recordset value) {
        return new JAXBElement<Recordset>(_RecordsetNode_QNAME, Recordset.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Fieldhistory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fieldhistory_node")
    public JAXBElement<Fieldhistory> createFieldhistoryNode(Fieldhistory value) {
        return new JAXBElement<Fieldhistory>(_FieldhistoryNode_QNAME, Fieldhistory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Linkage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "linkage_node")
    public JAXBElement<Linkage> createLinkageNode(Linkage value) {
        return new JAXBElement<Linkage>(_LinkageNode_QNAME, Linkage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Fielddefinition }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fielddefinition_node")
    public JAXBElement<Fielddefinition> createFielddefinitionNode(Fielddefinition value) {
        return new JAXBElement<Fielddefinition>(_FielddefinitionNode_QNAME, Fielddefinition.class, null, value);
    }

}
