//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.08 at 09:42:22 AM EDT 
//


package Coalesce.Framework.GeneratedJAXB;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the Coalesce.Framework.GeneratedJAXB package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: Coalesce.Framework.GeneratedJAXB
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Entity }
     * 
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link Entity.Section }
     * 
     */
    public Entity.Section createEntitySection() {
        return new Entity.Section();
    }

    /**
     * Create an instance of {@link Entity.Section.Recordset }
     * 
     */
    public Entity.Section.Recordset createEntitySectionRecordset() {
        return new Entity.Section.Recordset();
    }

    /**
     * Create an instance of {@link Entity.Section.Recordset.Record }
     * 
     */
    public Entity.Section.Recordset.Record createEntitySectionRecordsetRecord() {
        return new Entity.Section.Recordset.Record();
    }

    /**
     * Create an instance of {@link Entity.Section.Recordset.Record.Field }
     * 
     */
    public Entity.Section.Recordset.Record.Field createEntitySectionRecordsetRecordField() {
        return new Entity.Section.Recordset.Record.Field();
    }

    /**
     * Create an instance of {@link Entity.Linkagesection }
     * 
     */
    public Entity.Linkagesection createEntityLinkagesection() {
        return new Entity.Linkagesection();
    }

    /**
     * Create an instance of {@link NewDataSet }
     * 
     */
    public NewDataSet createNewDataSet() {
        return new NewDataSet();
    }

    /**
     * Create an instance of {@link Classification }
     * 
     */
    public Classification createClassification() {
        return new Classification();
    }

    /**
     * Create an instance of {@link Entity.Section.Recordset.Fielddefinition }
     * 
     */
    public Entity.Section.Recordset.Fielddefinition createEntitySectionRecordsetFielddefinition() {
        return new Entity.Section.Recordset.Fielddefinition();
    }

    /**
     * Create an instance of {@link Entity.Section.Recordset.Record.Field.Fieldhistory }
     * 
     */
    public Entity.Section.Recordset.Record.Field.Fieldhistory createEntitySectionRecordsetRecordFieldFieldhistory() {
        return new Entity.Section.Recordset.Record.Field.Fieldhistory();
    }

    /**
     * Create an instance of {@link Entity.Linkagesection.Linkage }
     * 
     */
    public Entity.Linkagesection.Linkage createEntityLinkagesectionLinkage() {
        return new Entity.Linkagesection.Linkage();
    }

}
